'use strict';
const quoteGenerator = {
  quotes: [
    'You can only coast if you\'re going downhill.', 
    'You do not rise to the occasion, you sink to your level of training.', 
    'Small strokes fell great oaks.',
    'Proper preparation prevents piss poor performance.', 
    'Take care of your gear and your gear will take care of you.', 
    'Slow is smooth, smooth is fast.', 
    'You are only as fast as your slowest guy.', 
    'Do today what others won\'t so you can do tomorrow what others can\'t.', 
    'The only easy day was yesterday. - US Navy SEALs', 
    'It pays to be a winner. - US Navy SEALs', 
    'The pity party was not well attended.', 
    'Reality has a way of shaping itself to your preconceived expectations.', 
    'Good judgement comes from experience. Experience comes from bad judgement. - Fortune Cookie', 
    '"By failing to prepare, you are preparing to fail." - Benjamin Franklin', 
    '"It\'s not the years in your life that count. It\'s the life in your years." - Abraham Lincoln',  
    '"Whether you think you can or you think you can\'t, you are right." - Henry Ford', 
    'The most powerful productivity tool ever invented is simply the word "no".',
    '"Invest the best hours of your day on the biggest opportunity, not the biggest problem." - Farnam Street',
    '"The biggest generator of long term results is learning to do things when you don\'t feel like doing them. If you let excuses or emotion drive behavior, you\'re cheating yourself. Put aside the excuses and start doing what you need to do." - Farnam Street',
    '“You\’re not going to succeed at stuff you don\’t want to do.” – Mark Bittman',
    '“Success isn\’t owned, it\’s rented. And the rent is due every day.” - Rory Vaden',
    '"I don\'t need time. What I need is a deadline." - Duke Ellington',
    '"If you don\’t produce, you won\’t thrive - no matter how skilled or talented you are." - Cal Newport',
    '"If you don\'t prioritize your life, someone else will." - Greg McKeown',
    '“Is your day by design or by default?” – J.D. Meier',
    '“It is not enough to be industrious; so are the ants. What are you industrious about?” - Henry David Thoreau',
    '“What the pupil must learn, if he learns anything at all, is that the world will do most of the work for you, provided you cooperate with it by identifying how it really works and aligning with those realities. If we do not let the world teach us, it teaches us a lesson.” — Joseph Tussman',
    '“If you wish to persuade, appeal to interest, rather than reason.” - Benjamin Franklin',
    '“It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid, instead of trying to be very intelligent.” - Charlie Munger',
    '“In my whole life, I have known no wise people (over a broad subject matter area) who didn\’t read all the time — none, zero. You\’d be amazed at how much Warren reads — and at how much I read. My children laugh at me. They think I\’m a book with a couple of legs sticking out.” - Charlie Munger',
    '“Character is fate.” - Heraclitus',
    '"Easy choices, hard life. Hard choices, easy life." - Jerzy Gregorek',
    '"Live as if you were living already for the second time and as if you had acted the first time as wrongly as you are about to act now." - Viktor Frankl',
    '“Let us conduct ourselves so that all men wish to be our friends and all fear to be our enemies.” - Alexander the Great',
    'It\’s not who you think you are or who you want to be. You are what you do consistently. - Unknown',
    '“We are what we repeatedly do, therefore, excellence is not an act but a habit.” - Aristotle',
    '“It is easier to act yourself into a new way of thinking, than it is to think yourself into a new way of acting.” - Millard Fuller',
    '"In the beginner\'s mind there are many possibilities; In the expert\'s, there are few." - Zen Master Shunryu Suzuki',
    'Our fatal mistake is waiting to be motivated before we take action. Action motivates. - Art of Manliness',
    'Live in a way that makes time your friend, not your enemy. - Unknown',
    '"I want to walk through life instead of being dragged through it." - Alanis Morissette',
    '"You cannot step in the same river twice." - Heraclitus',
    '"Our capacity to make peace with another person and with the world depends very much on our capacity to make peace with ourselves." - Thich Nhat Hanh',
    '“Don’t believe everything you think.” - BJ Miller, M.D',
    '“To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.” - Johann Wolfgang von Goethe',
    '“This is not your responsibility but it is your problem.” - Cheryl Strayed',
    '“Better to trip with the feet than with the tongue.” - Zeno',
    '"The purpose of a habit is to remove that action from self-negotiation. You no longer expend energy deciding whether to do it. You just do it. Good habits can range from telling the truth, to flossing." - Kevin Kelly',
    '"The world is changed by your example, not by your opinion." - @paulocoelho',
    '“Such as are your habitual thoughts, such also will be the character of your mind.” - Marcus Aurelius',
    '“Your mind will take the shape of what you frequently hold in thought.” - Marcus Aurelius',
    '"We suffer more in imagination than in reality." - Seneca',
    '“How does it help... to make troubles heavier by bemoaning them?”- Seneca',
    '“Everything hangs on one\’s thinking... a man is as unhappy as he has convinced himself he is.” - Seneca',
    '“There is good in everything, if only we look for it.” - Laura Ingalls Wilder',
    '“To a disciple who was forever complaining about others, the Master said, \‘If it is peace you want, seek to change yourself, not other people. It is easier to protect your feet with slippers than to carpet the whole of the earth.\’” - Anthony de Mello',
    '"Are you committed to being happy, no matter what happens to you?" - Tony Robbins',
    '“Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.” - Epicurus',
    '"Nothing is enough for the man to whom enough is too little." - Epicurus',
    '“To enjoy life, you don\’t need fancy nonsense, but you do need to control your time and realize that most things just aren\’t as serious as you make them out to be.” - Tim Ferriss',
    '"What you resist persists." - Carl Jung',
    '"Three grand essentials to happiness in this life are something to do, something to love, and something to hope for." - Joseph Addison',
    '"We have a right to our labor, not to the fruits of our labor." - Bhagavad Gita',
    '"Progress is impossible without change, and those who cannot change their minds cannot change anything." - George Bernard Shaw',
    '“Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.” - Jalaluddin Rumi',
    '“Care about what other people think and you\’ll always be their prisoner.” - Lao Tzu',
    '“You\’ll stop worrying what others think about you when you realize how seldom they do.” - David Foster Wallace'
  ],
  randomQuote: function() {
  let quote = Math.floor((Math.random() * quoteGenerator.quotes.length));
  return "<i> " + quoteGenerator.quotes[quote] + "</i>";
  }
};
(function() {
  $(document).ready(function() {
    $(quoteGenerator.randomQuote()).appendTo('#quote');
});
}());